import { WithContext } from "schema-dts";

import Image from "next/image";
import Link from "next/link";
import btnNextArrow from "~/images/icon/btn_nextArrow.svg";

import CourseUnit from "~/components/CourseUnit";
import PlanList from "~/components/PlanList";
import NewsListUnitSwiper from "~/components/NewsListUnitSwiper";
import NewsResType from "~/newsList/types";
import { format } from "date-fns";
import { newsListTypeMapping } from "~/utils/common";

// import type { Metadata } from 'next'
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

const Home = async () => {
  const jsonLd: WithContext<any> = {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "深入了解TAIDE計畫的背後策略、目標和里程碑。臺灣如何透過生成式AI技術，開創新的科技未來。",
    additionalName:
      "深入了解TAIDE計畫的背後策略、目標和里程碑。臺灣如何透過生成式AI技術，開創新的科技未來。",
    url: process.env.WEBSITE_DOMAIN,
    datePublished: "2023-03-02",
  };
  const newsListRes = await fetch(
    `${process.env.API_URL}/latest-updates?accessToken=TAIDE_!@%23qweASDzxc456RTYfgjVBN&frontSearchAll=&length=5&start=0`,
    {
      method: "POST",
      cache: "no-store",
    }
  );
  const { issuePlanList }: NewsResType.NewsListType = await newsListRes.json();

  return (
    <>
      <article className="bannerUnit">
        <div className="bannerUnit__body">
          <div className="bannerUnit__wrap">
            <div className="bannerUnit__left">
              <video width="320" height="240" autoPlay loop muted playsInline>
                <source
                  src={`${process.env.NEXT_PUBLIC_ASSET_PREFIX}/video/banner.mp4`}
                  type="video/mp4"
                />
              </video>
            </div>
          </div>
        </div>
      </article>

      <CourseUnit />
      <PlanList />

      <article className="teamUnit">
        <div className="teamUnit__body">
          <h2>TAIDE研發團隊</h2>
          <div className="row">
            <div className="cardTeam">
              <div className="cardTeam__item odd">
                <h3>模型鑄造組</h3>
                <div className="text">Basic Model Build Team</div>
                <div className="btn">
                  <Link
                    href={`${process.env.NEXT_PUBLIC_ASSET_PREFIX}/teamList#tag1`}
                  >
                    <span>了解更多</span>
                    <Image
                      src={btnNextArrow}
                      style={{ height: "auto" }}
                      alt="arrow"
                    />
                  </Link>
                </div>
              </div>
              <div className="cardTeam__item odd">
                <h3>應用領域組</h3>
                <div className="text">Application Field Team</div>
                <div className="btn">
                  <Link
                    href={`${process.env.NEXT_PUBLIC_ASSET_PREFIX}/teamList#tag2`}
                  >
                    <span>了解更多</span>
                    <Image
                      src={btnNextArrow}
                      style={{ height: "auto" }}
                      alt="arrow"
                    />
                  </Link>
                </div>
              </div>
            </div>
            <div className="cardTeam">
              <div className="cardTeam__item even">
                <h3>其他</h3>
                <div className="text">Others</div>
                <div className="btn">
                  <Link
                    href={`${process.env.NEXT_PUBLIC_ASSET_PREFIX}/teamList#tag3`}
                  >
                    <span>了解更多</span>
                    <Image
                      src={btnNextArrow}
                      style={{ height: "auto" }}
                      alt="arrow"
                    />
                  </Link>
                </div>
              </div>

              <div className="cardTeam__item even">
                <h3>前期參與</h3>
                <div className="text">Early Participation</div>
                <div className="btn">
                  <Link
                    href={`${process.env.NEXT_PUBLIC_ASSET_PREFIX}/teamList#tag4`}
                  >
                    <span>了解更多</span>
                    <Image
                      src={btnNextArrow}
                      style={{ height: "auto" }}
                      alt="arrow"
                    />
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </div>
      </article>
      <article className="newsListUnit">
        <div className="newsListUnit__body">
          <h2>TAIDE最新動態</h2>
          <div className="newsListUnit__wrap">
            <div className="newsListUnit__item max">
              <NewsListUnitSwiper bannerList={issuePlanList.slice(0, 2)} />
            </div>
            {issuePlanList.slice(2).map((e) => (
              <div className="newsListUnit__item" key={e.id}>
                <div className="photo">
                  <Link
                    href={`${process.env.NEXT_PUBLIC_ASSET_PREFIX}/newsList/newsDetail/${e.id}`}
                  ></Link>
                  <Image
                    src={`${process.env.NEXT_PUBLIC_NEWS_IMG_URL}/${e.id}`}
                    alt={e.title}
                    width={500}
                    height={500}
                  />
                  <div className="btn">
                    <Image
                      src={btnNextArrow}
                      style={{ height: "auto" }}
                      alt="arrow"
                    />
                  </div>
                </div>
                <div className="infoCon">
                  <h3>
                    <Link
                      href={`${process.env.NEXT_PUBLIC_ASSET_PREFIX}/newsList/newsDetail/${e.id}`}
                    >
                      {e.title}
                    </Link>
                  </h3>
                  {e.issueDate && (
                    <div className="date">
                      {format(new Date(e.issueDate), "yyyy.MM.dd")}
                    </div>
                  )}
                  {newsListTypeMapping[e.type] && (
                    <div className="tagUnit secondary">
                      {newsListTypeMapping[e.type]}
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </article>

      <article className="contactUnit home">
        <article className="contactUnit__body">
          <h2>
            <span>有任何想法？</span>
            <span>歡迎與我們聯絡</span>
          </h2>
          <div className="btn">
            <a href="mailto:TAIDE@narlabs.org.tw">
              <span>Contact TAIDE</span>
              <Image
                src={btnNextArrow}
                style={{ height: "auto" }}
                alt="arrow"
              />
            </a>
          </div>
        </article>
      </article>

      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify(jsonLd),
        }}
      ></script>
    </>
  );
};

export default Home;
